# Generated by Django 5.2.8 on 2025-11-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0005_remove_product_store_alter_product_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glovo_app.storemenu'),
        ),
    ]
