# Generated by Django 5.2.8 on 2025-11-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0007_alter_product_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo'),
        ),
    ]
